### ISSUE TITLE
Gitlab provider possibly constructs false token endpoint URL

### ISSUE THREAD

**Issue by byte-wolf** [pilcrowonpaper/arctic#188]
Hi there,

I recently stumbled upon the following error when implementing OAuth with the Gitlab provider (using a self-hosted gitlab instance):

```typescript
const token = await gitlab.validateAuthorizationCode(code);
```
```json
Failed to send request
err: {
    "type": "ArcticFetchError",
    "message": "Failed to send request: protocol must be http: or https:",
    "stack":
        Error: Failed to send request
            at new ArcticFetchError ([REDACTED]\node_modules\arctic\dist\request.js:91:9)
            at <anonymous> ([REDACTED]\node_modules\arctic\dist\request.js:23:19)
            at processTicksAndRejections (native:7:39)
        caused by: TypeError: protocol must be http: or https:
            at fetch (native)
            at <anonymous> ([REDACTED]\node_modules\arctic\dist\request.js:20:26)
            at sendTokenRequest ([REDACTED]\node_modules\arctic\dist\request.js:17:40)
            at <anonymous> ([REDACTED]\node_modules\arctic\dist\providers\gitlab.js:34:30)
            at validateAuthorizationCode ([REDACTED]\node_modules\arctic\dist\providers\gitlab.js:26:37)
            at <anonymous> ([REDACTED]/src/routes/login/gitlab/callback/+server.ts:34:74)
            at GET ([REDACTED]/src/routes/login/gitlab/callback/+server.ts:15:20)
            at <anonymous> ([REDACTED]/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:49:31)
            at render_endpoint ([REDACTED]/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:18:32)
            at <anonymous> ([REDACTED]/node_modules/@sveltejs/kit/src/runtime/server/respond.js:462:60)
    "originalLine": 74,
    "originalColumn": 10
}
```
(using SvelteKit)

I noticed, that the fetch request actually sends the request to "gitlab.redacted.comhttps://gitlab.redacted.com/oatuh/token".

So I did some digging in the source code and I found that the URL is constructed like this:
```typescript
this.tokenEndpoint = domain + `https://${domain}/oauth/token`;
```

Is it possible that this is a typo or an error in some other way, or is this intended?

**Comment by pilcrowonpaper** [comment]
Thanks, fixed with 2.2.1
