### ISSUE TITLE
Entra ID - client_id not included in the request to the token endpoint

### ISSUE THREAD

**Issue by jerevnp** [pilcrowonpaper/arctic#228]
When validating the authorization code against the token endpoint, Entra ID requires `client_id`(and `client_secret` for confidential apps) to be included in the body, as specified in their docs: https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow#request-an-access-token-with-a-client_secret

Currently, if a client secret is provided, the `client_id` will not be present in the request:

https://github.com/pilcrowonpaper/arctic/blob/c843cb456726f429613961a8ae1ec01818bf3dd3/src/client.ts#L79-L81

Additionally, I'm not sure if the `client_secret` provided as an `Authorization` header works as expected, but haven't had the time to test this yet.

On localhost return URIs these "broken" token requests seemingly work, but when the return URI is a real domain name, then Entra enforces stricter validation, and an error is returned:
```
OAuth2RequestError: OAuth request error: invalid_request
at createOAuth2RequestError (file:///app/server/node_modules/arctic/dist/request.js:87:12)
at sendTokenRequest (file:///app/server/node_modules/arctic/dist/request.js:36:23)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async OAuth2Client.validateAuthorizationCode (file:///app/server/node_modules/arctic/dist/client.js:66:24)
at async MicrosoftEntraId.validateAuthorizationCode (file:///app/server/node_modules/arctic/dist/providers/microsoft-entra-id.js:16:24)
at async Object.handler (file:///app/server/chunks/routes/login/callback.mjs:38:14)
at async Object.handler (file:///app/server/chunks/nitro/nitro.mjs:3088:19)
at async Server.toNodeHandle (file:///app/server/chunks/nitro/nitro.mjs:3359:7) {
  code: 'invalid_request',
  description: "AADSTS900144: The request body must contain the following parameter: 'client_id'. Trace ID: 145e9618-dc8d-41b1- 
 b14d-9db88d505000 Correlation ID: 83fa1ce5-c69a-477a-a6aa-449d6f3f3812 Timestamp: 2024-12-16 13:07:42Z",
  uri: 'https://login.microsoftonline.com/error?code=900144',
  state: null
}
````

As this logic is in the client itself and not provider-specific, would fixing this specific "nuance" of Entra ID perhaps break other providers...?

**Comment by jerevnp** [comment]
Tested a fix by just adding the `client_id` into the body, and that was not enough for Entra:

```
12-16-2024 05:12:56 PM OAuth2RequestError: OAuth request error: invalid_client
12-16-2024 05:12:56 PM     at createOAuth2RequestError (file:///app/server/chunks/nitro/nitro.mjs:4821:10)
12-16-2024 05:12:56 PM     at sendTokenRequest (file:///app/server/chunks/nitro/nitro.mjs:4773:19)
12-16-2024 05:12:56 PM     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
12-16-2024 05:12:56 PM     at async MicrosoftEntraId.validateAuthorizationCode (file:///app/server/chunks/nitro/nitro.mjs:4987:20)
12-16-2024 05:12:56 PM     at async Object.handler (file:///app/server/chunks/routes/login/callback.mjs:38:14)
12-16-2024 05:12:56 PM     at async Object.handler (file:///app/server/chunks/nitro/nitro.mjs:3088:19)
12-16-2024 05:12:56 PM     at async Server.toNodeHandle (file:///app/server/chunks/nitro/nitro.mjs:3359:7) {
12-16-2024 05:12:56 PM   code: 'invalid_client',
12-16-2024 05:12:56 PM   description: "AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'. Trace ID: 98feee38-c2ff-460e-b6ba-1af22c284d00 Correlation ID: ede10dd0-3702-410d-a039-c9840341e2bf Timestamp: 2024-12-16 15:12:56Z",
12-16-2024 05:12:56 PM   uri: 'https://login.microsoftonline.com/error?code=7000218',
12-16-2024 05:12:56 PM   state: null
12-16-2024 05:12:56 PM }
```

**Comment by jerevnp** [comment]
After fiddling with the `client_secret` body attribute, noticed that this whole thing was actually an user error 😄 My environment variable was `ENTRA_CLIENT_SECTET` and not `ENTRA_CLIENT_SECRET` which worked locally when supplied with the `.env`, but in AWS environment that was coming from Secrets Manager with the correct typing.

So works as intended 👍
